---
blank_issues_enabled: false
contact_links:
  - about: Join our community on Slack. Get answers and share ideas with kindreds.
    name: ðŸ’¬ Slack Channel
    url: 'https://app.slack.com/client/T01ABCG4NK1/C01NN74H0LW/details/'
  - about: For the fastest, most-thorough solutions we encourage you to consider paid support.
    name: ðŸ“Ÿ Paid Support
    url: https://megabyte.space/commercial-support
